--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 6 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : work
-- Host name     : SERING
-- User name     : peterj
-- Time stamp    : Fri Aug 01 11:18:08 2014
--
-- Designed by   : 
-- Company       : HDL Works
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.Reg1en
-- Last modified : Fri Mar 30 11:53:18 2012.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity Reg1en is
  port (
    Clk : in     std_logic;
    D   : in     std_logic;
    En  : in     std_logic;
    Q   : out    std_logic;
    Rst : in     std_logic);
end entity Reg1en;

--------------------------------------------------------------------------------
-- Object        : Architecture design.Reg1en.a0
-- Last modified : Fri Mar 30 11:53:18 2012.
--------------------------------------------------------------------------------


architecture a0 of Reg1en is

begin
   Process (Clk, Rst)
   Begin       
      If Rst = '1' Then
         Q <= '0';
      ElsIf Rising_Edge(Clk) Then
         If En = '1' Then
            Q <= D;
         End If;
      End If;
   End Process;
end architecture a0 ; -- of Reg1en

