--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 7.4 Revision 9 from HDL Works B.V.
--
-- Ease library  : work
-- HDL library   : work
-- Host name     : SERING
-- User name     : peterj
-- Time stamp    : Tue Aug 13 12:20:16 2013
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity work.DummySource
-- Last modified : Mon Aug 12 10:50:15 2013.
--------------------------------------------------------------------------------

library ieee, work;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wr_fabric_pkg.all;

entity wb_DummySource is
  port(
    src_i : out    t_wrf_source_in;
    src_o : in     t_wrf_source_out);
end entity wb_DummySource;

--------------------------------------------------------------------------------
-- Object        : Architecture work.DummySource.rtl
-- Last modified : Mon Aug 12 10:50:15 2013.
--------------------------------------------------------------------------------


architecture rtl of wb_DummySource is

begin

	src_i <= c_dummy_src_in;

end architecture rtl ; -- of DummySource

