--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 7.4 Revision 9 from HDL Works B.V.
--
-- Ease library  : work
-- HDL library   : work
-- Host name     : SERING
-- User name     : peterj
-- Time stamp    : Tue Aug 13 12:20:16 2013
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity work.DummySlave
-- Last modified : Thu Aug 01 15:14:37 2013.
--------------------------------------------------------------------------------

library ieee, work;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.genram_pkg.all;
use work.wishbone_pkg.all;

entity wb_DummySlave is
  port(
    Slave_i : in     t_wishbone_slave_in;
    Slave_o : out    t_wishbone_slave_out);
end entity wb_DummySlave;

--------------------------------------------------------------------------------
-- Object        : Architecture work.DummySlave.rtl
-- Last modified : Thu Aug 01 15:14:37 2013.
--------------------------------------------------------------------------------


architecture rtl of wb_DummySlave is
begin
-- Slave input wishbone signals
--  Slave_i.cyc                                 <= open;--'0';
--  Slave_i.stb                                 <= open;--'0';
--  Slave_i.adr                                 <= open;--(Others => '0');
--  Slave_i.sel                                 <= open;--"0000";
--  Slave_i.we                                  <= open;--'0';
--  Slave_i.dat                                 <= open;--(Others => '0');

-- Slave output wishbone signals
  Slave_o.ack                                <= '0';
  Slave_o.err                                <= '0';
  Slave_o.rty                                <= '0';
  Slave_o.stall                              <= '0';
  Slave_o.int                                <= '0';
  Slave_o.dat                                <= (Others => '0');
end architecture rtl ; -- of DummySlave

